const $=id=>document.getElementById(id),escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});let data;try{data=await response.json()}catch{throw new Error('服务响应异常')}if(response.status===401){location.replace('/admin-login.html');throw new Error('管理员会话已过期')}if(!response.ok)throw new Error(data.error||'请求失败');return data};
let currentView='overview',activeJob=null,pollTimer=null,cache={trains:[]};
const meta={overview:['运营总览','实时掌握铁路客票系统运行状态'],trains:['车次与库存','按运行实例查看席位位图与占用情况'],orders:['订单与乘客','查看交易流水及乘客账户档案'],waitlist:['候补队列','监控队列顺序、公平保护和兑现状态'],buffer:['流量缓冲','监控数据库持久化削峰队列与消费延迟'],ai:['AI 订票员','创建真实数据库负载，验证库存与候补能力']};
function toast(message,error=false){const el=$('adminToast');el.textContent=message;el.className='admin-toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3000)}
function number(v){return Number(v||0).toLocaleString('zh-CN')}function percent(v){return Math.max(0,Math.min(100,Number(v||0)))}
function statusPill(value){const map={ON_SALE:['sale','售票中'],PLANNED:['pending','计划中'],STOP_SALE:['closed','停售'],PAID:['paid','已支付'],PENDING_PAYMENT:['pending','待支付'],CANCELLED:['cancelled','已取消'],TIMEOUT:['closed','已超时'],REFUNDED:['closed','已退款'],WAITLIST_PENDING:['pending','候补中'],WAITLIST_FAILED:['closed','候补失败'],WAITING:['waiting','排队中'],MATCHING:['pending','匹配中'],MATCHED_HOLD:['pending','已占座'],FULFILLED:['paid','已兑现'],EXPIRED:['closed','已过期']},m=map[value]||['closed',value];return `<span class="state-pill ${m[0]}">${m[1]}</span>`}
function showView(view){currentView=view;history.replaceState(null,'',`#${view}`);document.querySelectorAll('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));[$('viewTitle').textContent,$('viewSubtitle').textContent]=meta[view];loadView(view)}
async function loadView(view){try{if(view==='overview')await loadOverview();if(view==='trains')await loadTrains();if(view==='orders')await Promise.all([loadOrders(),loadPassengers()]);if(view==='waitlist')await loadWaits();if(view==='buffer')await loadBuffer();if(view==='ai')await loadAiOptions()}catch(error){toast(error.message,true)}}
async function loadOverview(){const data=await api('/api/admin/overview');$('adminHealth').className='system-state';$('adminHealth').innerHTML='<i></i><span>数据库运行正常</span>';$('mRuns').textContent=number(data.metrics.runs);$('mOnSale').textContent=`${number(data.metrics.on_sale)} 趟正在售票`;$('mSeats').textContent=number(data.metrics.seats);$('mOccupancy').textContent=`${data.metrics.occupancy_rate}% 已占用`;$('mOrders').textContent=number(data.metrics.orders);$('mPaid').textContent=`${number(data.metrics.paid_orders)} 笔已支付`;$('mWaits').textContent=number(data.metrics.waiting);$('mUsers').textContent=`${number(data.metrics.passengers)} 位注册乘客`;$('waitBadge').textContent=data.metrics.waiting;renderPulse(data.pulse);renderDonut(data.order_statuses,data.metrics.orders);renderTopTrains(data.top_trains);renderActivity(data.activity)}
function renderPulse(rows){const max=Math.max(1,...rows.flatMap(r=>[Number(r.orders),Number(r.inventory)]));$('pulseChart').innerHTML=rows.map(r=>`<div class="bar-group" title="${r.bucket}: ${r.orders} 订单事件 / ${r.inventory} 库存事件"><i style="height:${Math.max(2,Number(r.orders)/max*100)}%"></i><i style="height:${Math.max(2,Number(r.inventory)/max*100)}%"></i><span>${String(r.bucket).slice(11,16)}</span></div>`).join('')||'<div class="empty-cell">暂无近期事件</div>'}
function renderDonut(rows,total){const colors=['#337cf6','#20b486','#f19a42','#9aa5b5','#8a6cf1','#e85c66'],sum=Math.max(1,rows.reduce((a,r)=>a+Number(r.count),0));let at=0,parts=rows.map((r,i)=>{const start=at;at+=Number(r.count)/sum*100;return `${colors[i%colors.length]} ${start}% ${at}%`});$('orderDonut').innerHTML=`<div class="donut" style="background:conic-gradient(${parts.join(',')||'#edf1f5 0 100%'})"><div class="donut-center"><b>${number(total)}</b><span>总订单</span></div></div><div class="donut-legend">${rows.slice(0,6).map((r,i)=>`<span><i style="background:${colors[i]}"></i>${statusPillText(r.order_status)}<b>${r.count}</b></span>`).join('')}</div>`}
function statusPillText(v){return ({PENDING_PAYMENT:'待支付',PAID:'已支付',CANCELLED:'已取消',TIMEOUT:'已超时',REFUNDED:'已退款',REFUNDING:'退款中'})[v]||v}
function renderTopTrains(rows){$('topTrains').innerHTML=rows.map((r,i)=>`<div class="rank-row"><i>${i+1}</i><b>${escapeHtml(r.train_no)}</b><span class="rank-route">${escapeHtml(r.origin_name||'—')} → ${escapeHtml(r.destination_name||'—')}</span><span class="load-bar"><i style="width:${percent(r.occupancy_rate)}%"></i></span><em>${r.occupancy_rate}%</em></div>`).join('')||'<div class="empty-cell">暂无车次</div>'}
function renderActivity(rows){$('activityFeed').innerHTML=rows.map(r=>`<div class="activity-item"><i>${r.category==='ORDER'?'单':'座'}</i><div><b>${escapeHtml(activityText(r.event_type))}</b><span>${escapeHtml(r.subject)} · ${escapeHtml(r.occurred_at)}</span></div></div>`).join('')||'<div class="empty-cell">暂无审计事件</div>'}function activityText(v){return ({HOLD:'库存预占',CONFIRM:'库存确认',RELEASE:'库存释放',ORDER_CREATED:'订单创建',PAYMENT_CONFIRMED:'支付确认',ORDER_CANCELLED:'订单取消'})[v]||v}
async function loadTrains(){const query=$('trainSearch').value.trim(),params=new URLSearchParams({date:$('trainDate').value,q:query});const rows=await api(`/api/admin/trains?${params}`);cache.trains=rows;$('trainCount').textContent=query?`精确匹配 ${rows.length} 趟运行实例 · 输入车次时跨日期查询`:`共 ${rows.length} 趟运行实例`;$('trainRows').innerHTML=rows.map(r=>`<tr><td><strong>${escapeHtml(r.train_no)}</strong><br><small>#${r.run_id} · ${escapeHtml(r.service_date)}</small></td><td class="route-cell">${escapeHtml(r.origin_name||'—')} → ${escapeHtml(r.destination_name||'—')}<small>${r.departure_at?String(r.departure_at).slice(11,16):'—'} — ${r.arrival_at?String(r.arrival_at).slice(11,16):'—'} · ${r.stop_count} 站</small></td><td>${statusPill(r.run_status)}</td><td>${r.occupied_seats} / ${r.total_seats}</td><td><span class="mini-load"><i style="width:${percent(r.occupancy_rate)}%"></i></span>${r.occupancy_rate}%</td><td><button class="row-action" onclick="loadSeats(${r.run_id})">查看库存</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty-cell">没有匹配车次</td></tr>'}
async function loadSeats(runId,fromOrder='',toOrder=''){$('seatDetail').innerHTML='<div class="detail-empty"><span>↻</span><h3>读取区间库存…</h3></div>';try{const params=new URLSearchParams({runId});if(fromOrder)params.set('fromOrder',fromOrder);if(toOrder)params.set('toOrder',toOrder);const data=await api(`/api/admin/train-seats?${params}`),run=data.run,from=Number(data.from_order),to=Number(data.to_order),fromStop=data.stops.find(s=>Number(s.station_order)===from),toStop=data.stops.find(s=>Number(s.station_order)===to);cache.inventoryStops=data.stops;$('seatDetail').innerHTML=`<div class="seat-detail-head"><b>${escapeHtml(run.train_no)}</b><span>${escapeHtml(fromStop?.station_name)} → ${escapeHtml(toStop?.station_name)} · 区间实时库存</span><div class="inventory-range"><select id="inventoryFrom" onchange="changeInventoryFrom(${runId})">${data.stops.slice(0,-1).map(s=>`<option value="${s.station_order}" ${Number(s.station_order)===from?'selected':''}>${escapeHtml(s.station_name)}</option>`).join('')}</select><i>→</i><select id="inventoryTo" onchange="loadSeats(${runId},document.getElementById('inventoryFrom').value,this.value)">${data.stops.filter(s=>Number(s.station_order)>from).map(s=>`<option value="${s.station_order}" ${Number(s.station_order)===to?'selected':''}>${escapeHtml(s.station_name)}</option>`).join('')}</select></div><div class="inventory-legend"><i class="free"></i>本区间可售 <i class="used"></i>本区间已占用</div></div><div class="seat-groups">${data.groups.map(g=>{const seats=data.seats.filter(s=>String(s.carriage_no)===String(g.carriage_no)&&s.seat_type_name===g.seat_type_name);return `<div class="seat-group inventory-group"><div class="seat-group-head"><b>${g.carriage_no} 车 · ${escapeHtml(g.seat_type_name)}</b><span><strong>${g.free_interval}</strong> 可售 / ${g.total_seats} 席</span></div><div class="load-bar"><i style="width:${percent(g.occupancy_rate)}%"></i></div><div class="seat-map-admin">${seats.map(s=>`<span class="${s.seat_status==='FREE'?'free':'used'}" title="${escapeHtml(s.seat_no)} · ${s.seat_status==='FREE'?'本区间可售':'与本区间存在占用冲突'} · 位图 ${s.occupied_mask}">${escapeHtml(s.seat_no)}</span>`).join('')}</div></div>`}).join('')||'<div class="detail-empty"><h3>该车次尚未配置席位</h3></div>'}</div>`}catch(error){$('seatDetail').innerHTML='<div class="detail-empty"><span>!</span><h3>库存读取失败</h3></div>';toast(error.message,true)}}
function changeInventoryFrom(runId){const from=Number($('inventoryFrom').value),valid=(cache.inventoryStops||[]).filter(s=>Number(s.station_order)>from);$('inventoryTo').innerHTML=valid.map(s=>`<option value="${s.station_order}">${escapeHtml(s.station_name)}</option>`).join('');const to=valid.at(-1)?.station_order;if(to)loadSeats(runId,from,to)}
async function loadOrders(){const params=new URLSearchParams({status:$('orderStatus').value,sort:$('orderSort').value}),rows=await api(`/api/admin/orders?${params}`);$('orderRows').innerHTML=rows.map(r=>`<tr><td class="record-no"><small>${r.record_type==='WAITLIST'?'候补':'订单'}</small><span>${escapeHtml(r.order_no)}</span></td><td><strong>${escapeHtml(r.passenger_name)}</strong><small>${escapeHtml(r.username)}</small></td><td class="route-cell"><strong>${escapeHtml(r.train_no)}</strong> ${escapeHtml(r.from_station_name)} → ${escapeHtml(r.to_station_name)}<small>${escapeHtml(r.service_date)}</small></td><td><strong>${escapeHtml(r.seat_type_name)}</strong><small>${r.record_type==='WAITLIST'?'待分配':`${r.carriage_no||'-'}车 ${escapeHtml(r.seat_no||'待分配')}`}</small></td><td class="money-cell">¥${r.total_amount}</td><td>${statusPill(r.order_status)}</td><td>${escapeHtml(r.created_at)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty-cell">暂无订单</td></tr>'}
async function loadPassengers(){const q=$('passengerSearch').value,rows=await api(`/api/admin/passengers?q=${encodeURIComponent(q)}`);$('passengerRows').innerHTML=rows.map(r=>`<tr><td>#${r.passenger_id}</td><td><strong>${escapeHtml(r.passenger_name)}</strong><br><small>${escapeHtml(r.document_type)}</small></td><td>${escapeHtml(r.username)}<br><small>#${r.owner_user_id}</small></td><td>${statusPill(r.passenger_status==='ACTIVE'?'ON_SALE':'CANCELLED')}</td><td>${r.order_count}</td><td>${r.wait_count}</td><td>${escapeHtml(r.created_at)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty-cell">暂无乘客</td></tr>'}
async function loadWaits(){const data=await api('/api/admin/waits');$('wWaiting').textContent=number(data.summary.waiting);$('wMatched').textContent=number(data.summary.fulfilled);$('wProtected').textContent=number(data.summary.protected);$('wSkipped').textContent=number(data.summary.skipped);$('waitBadge').textContent=data.summary.waiting;$('waitRows').innerHTML=data.rows.map(r=>`<tr><td><span class="queue-no">#${r.queue_position||'—'}</span>${String(r.fairness_protected)==='1'?'<br><span class="state-pill protected">公平保护</span>':''}</td><td>${escapeHtml(r.wait_request_no)}<br><small>#${r.wait_request_id}</small></td><td><strong>${escapeHtml(r.train_no)}</strong><br><small>${escapeHtml(r.seat_type_name)}</small></td><td>${escapeHtml(r.from_station_name)} → ${escapeHtml(r.to_station_name)}</td><td>${r.passenger_count}</td><td>${statusPill(r.wait_status)}</td><td>${r.retry_count} / ${r.skip_count}</td><td>${escapeHtml(r.cutoff_at)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty-cell">候补队列为空</td></tr>'}
async function loadBuffer(){const data=await api('/api/admin/buffer');$('bQueued').textContent=number(data.summary.queued);$('bProcessing').textContent=number(data.summary.processing);$('bSucceeded').textContent=number(data.summary.succeeded);$('bLatency').textContent=`${number(data.summary.avg_ms)} ms`;$('bufferRows').innerHTML=data.rows.map(r=>`<tr><td><strong>${escapeHtml(r.request_no)}</strong><br><small>#${r.booking_request_id}</small></td><td>${escapeHtml(r.passenger_name)}<br><small>${escapeHtml(r.username)}</small></td><td class="route-cell"><strong>${escapeHtml(r.train_no)}</strong> ${escapeHtml(r.from_station_name)} → ${escapeHtml(r.to_station_name)}</td><td>${escapeHtml(r.seat_type_name)}</td><td>${bufferStatus(r.request_status)}</td><td>${r.attempt_count}</td><td>${Math.round(Number(r.elapsed_ms||0))} ms</td><td><small>${escapeHtml(r.error_code||'—')}</small></td></tr>`).join('')||'<tr><td colspan="8" class="empty-cell">缓冲区暂无请求</td></tr>'}
function bufferStatus(value){const mapped={QUEUED:'WAITING',PROCESSING:'MATCHING',SUCCEEDED:'FULFILLED',FAILED:'CANCELLED',CANCELLED:'CANCELLED'};return statusPill(mapped[value]||value)}
async function loadAiOptions(){const data=await api('/api/admin/ai/options');cache.aiOptions=data;cache.aiStops=cache.aiStops||{};$('aiRunList').innerHTML=data.runs.map(r=>`<option value="${escapeHtml(r.train_no)}">${escapeHtml(r.origin_name)} → ${escapeHtml(r.destination_name)}</option>`).join('');matchAiRun();renderJobs(data.jobs);await loadAiOrders();if(data.jobs[0]&&data.jobs[0].status==='RUNNING'){activeJob=data.jobs[0].job_id;showJob(data.jobs[0]);startPolling()}}
function showAiRunMatch(value){
  const run=cache.aiOptions?.runs.find(r=>String(r.train_no).toUpperCase()===value);
  $('aiRun').value=run?.run_id||'';
  $('aiRunMatch').textContent=run
    ?`${run.train_no} · ${run.origin_name} → ${run.destination_name} · ${run.service_date}`
    :(value?'正在精确查找车次…':'输入车次号后自动匹配');
  $('aiRunMatch').classList.toggle('matched',!!run);
  updateSeatTypes();
  updateAiStops(run?.run_id||'');
  return run;
}
function matchAiRun(){
  const value=$('aiRunSearch').value.trim().toUpperCase();
  if(showAiRunMatch(value)||!value)return;
  clearTimeout(window.aiRunTimer);
  window.aiRunTimer=setTimeout(async()=>{
    try{
      const exact=await api(`/api/admin/ai/options?q=${encodeURIComponent(value)}`);
      if($('aiRunSearch').value.trim().toUpperCase()!==value)return;
      if(!exact.runs.length){
        $('aiRunMatch').textContent='未找到可售的完整车次号';
        $('aiRunMatch').classList.remove('matched');
        return;
      }
      const knownRuns=new Set(cache.aiOptions.runs.map(r=>String(r.run_id)));
      cache.aiOptions.runs.push(...exact.runs.filter(r=>!knownRuns.has(String(r.run_id))));
      cache.aiOptions.seat_types.push(...exact.seat_types.filter(x=>
        !cache.aiOptions.seat_types.some(y=>
          String(y.run_id)===String(x.run_id)&&
          String(y.seat_type_id)===String(x.seat_type_id)
        )
      ));
      showAiRunMatch(value);
    }catch(error){
      $('aiRunMatch').textContent=error.message;
    }
  },180);
}
function updateSeatTypes(){const runId=$('aiRun').value,types=cache.aiOptions?.seat_types.filter(x=>String(x.run_id)===String(runId))||[];$('aiSeatType').innerHTML='<option value="">选择席别</option>'+types.map(x=>`<option value="${x.seat_type_id}">${escapeHtml(x.seat_type_name)} · ${x.free_full_route}/${x.total_seats} 全程空闲</option>`).join('')}
async function updateAiStops(runId){
  if(!runId){$('aiFromOrder').innerHTML='<option value="">先选择车次</option>';$('aiToOrder').innerHTML='<option value="">先选择上车站</option>';return}
  try{
    const stops=cache.aiStops[runId]||(cache.aiStops[runId]=await api(`/api/runs/${runId}/stops`));
    $('aiFromOrder').innerHTML=stops.slice(0,-1).map(s=>`<option value="${s.station_order}">${escapeHtml(s.station_name)}</option>`).join('');
    $('aiFromOrder').value=String(stops[0]?.station_order||'');
    updateAiToStops();
    $('aiToOrder').value=String(stops.at(-1)?.station_order||'');
  }catch(error){toast(error.message,true)}
}
function updateAiToStops(){
  const runId=$('aiRun').value,from=Number($('aiFromOrder').value),stops=cache.aiStops?.[runId]||[];
  const valid=stops.filter(s=>Number(s.station_order)>from);
  $('aiToOrder').innerHTML=valid.map(s=>`<option value="${s.station_order}">${escapeHtml(s.station_name)}</option>`).join('')||'<option value="">没有可选下车站</option>';
}
async function calculateAiUsers(){const runId=$('aiRun').value,seatTypeId=$('aiSeatType').value,fromOrder=$('aiFromOrder').value,toOrder=$('aiToOrder').value,keep=Number($('aiKeepSeats').value);if(!runId||!seatTypeId||!fromOrder||!toOrder)return toast('请先选择车次、区间和席别',true);if(!Number.isInteger(keep)||keep<1)return toast('预留张数至少为 1',true);try{const row=await api(`/api/availability?${new URLSearchParams({runId,seatTypeId,fromOrder,toOrder})}`),available=Number(row.available_seats),users=available-keep;if(users<1)return toast(`该区间当前只有 ${available} 张余票，无法预留 ${keep} 张后再预置`,true);if(users>500)return toast(`需要预置 ${users} 人，超过单次上限 500，请缩小席位范围`,true);$('aiTargetUsers').value=users;$('aiTargetHint').textContent=`实时余票 ${available} 张；预置 ${users} 人后，目标剩余约 ${keep} 张`;$('aiConcurrency').value=2;$('aiPayRate').value=100;$('payOutput').textContent='100%';$('aiWaitlist').checked=false;toast(`已按 ${available} 张余票计算出 ${users} 名 AI 订票员`)}catch(error){toast(error.message,true)}}
async function startAi(){const mode=document.querySelector('[name=aiMode]:checked').value,body={mode,users:Number(mode==='targeted'?$('aiTargetUsers').value:$('aiUsers').value),concurrency:Number($('aiConcurrency').value),payRate:Number($('aiPayRate').value),waitlist:$('aiWaitlist').checked};if(mode==='targeted'){body.runId=$('aiRun').value;body.seatTypeId=$('aiSeatType').value;body.fromOrder=$('aiFromOrder').value;body.toOrder=$('aiToOrder').value;if(!body.runId||!body.seatTypeId||!body.fromOrder||!body.toOrder)return toast('请选择目标车次、区间和席别',true)}$('startAI').disabled=true;try{const job=await api('/api/admin/ai/start',{method:'POST',body:JSON.stringify(body)});activeJob=job.job_id;showJob(job);startPolling();toast('AI 订票任务已启动')}catch(error){toast(error.message,true);$('startAI').disabled=false}}
function showJob(job){$('jobEmpty').classList.add('hidden');$('jobProgress').classList.remove('hidden');const done=Number(job.completed||0),total=Math.max(1,Number(job.users||1)),pct=Math.round(done/total*100);$('jobPercent').textContent=pct+'%';$('progressRing').style.background=`conic-gradient(var(--blue) ${pct}%,#edf1f5 ${pct}%)`;$('jHeld').textContent=job.held||0;$('jPaid').textContent=job.paid||0;$('jWaited').textContent=job.waitlisted||0;$('jFailed').textContent=job.failed||0;$('jRps').textContent=`${Number(job.rps||0).toFixed(1)} req/s`;$('jobState').className='job-state '+(job.status==='RUNNING'?'running':'done');$('jobState').textContent=job.status==='RUNNING'?'运行中':job.status==='COMPLETED'?'已完成':'异常结束';$('jobErrors').innerHTML=(job.errors||[]).slice(-3).map(e=>`<div>· ${escapeHtml(e)}</div>`).join('');if(job.status!=='RUNNING'){$('startAI').disabled=false;clearInterval(pollTimer);pollTimer=null}}
function renderJobs(jobs){$('jobRows').innerHTML=jobs.map(j=>`<tr><td>${escapeHtml(j.job_id)}</td><td>${j.mode==='random'?'随机抢票':'定向压测'}</td><td>${j.users} / ${j.concurrency}</td><td>${j.held}</td><td>${j.paid}</td><td>${j.waitlisted}</td><td>${j.failed}</td><td>${Number(j.elapsed||0).toFixed(1)}s</td><td>${j.status==='RUNNING'?statusPill('MATCHING'):statusPill(j.status==='COMPLETED'?'FULFILLED':'CANCELLED')}</td></tr>`).join('')||'<tr><td colspan="9" class="empty-cell">暂无任务记录</td></tr>'}
async function loadAiOrders(){const params=new URLSearchParams({trainNo:$('aiRefundTrain').value.trim().toUpperCase(),q:$('aiOrderSearch').value});const rows=await api(`/api/admin/ai/orders?${params}`);cache.aiOrders=rows;$('aiOrderRows').innerHTML=rows.map(r=>{const actionable=['PAID','PENDING_PAYMENT'].includes(r.order_status);return `<tr><td class="ai-user-cell"><b>${escapeHtml(r.passenger_name)}</b><small>${escapeHtml(r.username)}</small></td><td>${escapeHtml(r.order_no)}<br><small>#${r.order_id}</small></td><td class="route-cell"><strong>${escapeHtml(r.train_no)}</strong> ${escapeHtml(r.from_station_name)} → ${escapeHtml(r.to_station_name)}</td><td>${escapeHtml(r.seat_type_name)}<br><small>${r.carriage_no||'-'}车 ${escapeHtml(r.seat_no||'待分配')}</small></td><td>¥${r.total_amount}</td><td>${statusPill(r.order_status)}</td><td>${escapeHtml(r.created_at)}</td><td><button class="danger-action" onclick="refundAiOrder(${r.order_id})" ${actionable?'':'disabled'}>${r.order_status==='PENDING_PAYMENT'?'取消预占':'退票'}</button></td></tr>`}).join('')||'<tr><td colspan="8" class="empty-cell">没有匹配的 AI 订单</td></tr>'}
async function refundAiOrder(orderId){const order=cache.aiOrders.find(r=>String(r.order_id)===String(orderId));if(!order||!['PAID','PENDING_PAYMENT'].includes(order.order_status))return;if(!confirm(`确定要为 AI 乘客“${order.passenger_name}”${order.order_status==='PAID'?'退票':'取消预占'}吗？`))return;try{await api(`/api/admin/ai/orders/${orderId}/refund`,{method:'POST',body:'{}'});toast('AI 订单已处理，库存已经释放');await loadAiOrders()}catch(error){toast(error.message,true)}}
async function updateBatchRefundStops(){const trainNo=$('batchRefundTrain').value.trim().toUpperCase(),run=cache.aiOptions?.runs.find(r=>String(r.train_no).toUpperCase()===trainNo);if(!run){$('batchRefundFrom').innerHTML='<option value="">先输入完整车次号</option>';$('batchRefundTo').innerHTML='<option value="">先选择上车站</option>';return}try{const stops=cache.aiStops[run.run_id]||(cache.aiStops[run.run_id]=await api(`/api/runs/${run.run_id}/stops`));$('batchRefundFrom').dataset.runId=run.run_id;$('batchRefundFrom').innerHTML=stops.slice(0,-1).map(s=>`<option value="${s.station_order}">${escapeHtml(s.station_name)}</option>`).join('');$('batchRefundFrom').value=String(stops[0]?.station_order||'');updateBatchRefundToStops();$('batchRefundTo').value=String(stops.at(-1)?.station_order||'')}catch(error){toast(error.message,true)}}
function updateBatchRefundToStops(){const runId=$('batchRefundFrom').dataset.runId,from=Number($('batchRefundFrom').value),stops=cache.aiStops?.[runId]||[];$('batchRefundTo').innerHTML=stops.filter(s=>Number(s.station_order)>from).map(s=>`<option value="${s.station_order}">${escapeHtml(s.station_name)}</option>`).join('')||'<option value="">没有可选下车站</option>'}
async function batchRefund(){const trainNo=$('batchRefundTrain').value.trim().toUpperCase(),count=Number($('batchRefundCount').value),run=cache.aiOptions?.runs.find(r=>String(r.train_no).toUpperCase()===trainNo),fromOrder=Number($('batchRefundFrom').value),toOrder=Number($('batchRefundTo').value);if(!run)return toast('请输入完整且可售的车次号',true);if(!fromOrder||!toOrder||fromOrder>=toOrder)return toast('请选择有效的退票区间',true);const stops=cache.aiStops?.[run.run_id]||[],fromName=stops.find(s=>Number(s.station_order)===fromOrder)?.station_name,toName=stops.find(s=>Number(s.station_order)===toOrder)?.station_name;if(!confirm(`将从 ${run.train_no} ${fromName} → ${toName} 的 AI 订单中随机处理最多 ${count} 笔，是否继续？`))return;const button=$('batchRefundButton');button.disabled=true;try{const result=await api('/api/admin/ai/refund-batch',{method:'POST',body:JSON.stringify({runId:run.run_id,fromOrder,toOrder,count})});toast(`已处理 ${result.completed} 笔该区间 AI 订单`);$('aiRefundTrain').value=run.train_no;await loadAiOrders()}catch(error){toast(error.message,true)}finally{button.disabled=false}}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(async()=>{if(!activeJob)return;try{const job=await api(`/api/admin/ai/jobs/${activeJob}`);showJob(job);const jobs=await api('/api/admin/ai/jobs');renderJobs(jobs)}catch(error){toast(error.message,true)}},900)}
document.querySelectorAll('#adminNav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>showView(b.dataset.goto));document.querySelectorAll('.subtabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.subtabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.subview').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.sub).classList.add('active')});document.querySelectorAll('[name=aiMode]').forEach(r=>r.onchange=()=>{const targeted=r.value==='targeted'&&r.checked;$('targetFields').classList.toggle('disabled',!targeted);$('randomUserField').classList.toggle('hidden',targeted)});
$('loadTrains').onclick=loadTrains;$('trainSearch').oninput=()=>{clearTimeout(window.trainTimer);window.trainTimer=setTimeout(loadTrains,300)};$('orderStatus').onchange=loadOrders;$('passengerSearch').oninput=()=>{clearTimeout(window.passengerTimer);window.passengerTimer=setTimeout(loadPassengers,300)};$('loadWaits').onclick=loadWaits;$('loadBuffer').onclick=loadBuffer;$('aiRun').onchange=updateSeatTypes;$('aiFromOrder').onchange=updateAiToStops;$('aiCalculate').onclick=calculateAiUsers;$('aiPayRate').oninput=()=>{$('payOutput').textContent=$('aiPayRate').value+'%'};$('startAI').onclick=startAi;$('refreshAiOrders').onclick=loadAiOrders;$('aiRefundTrain').oninput=()=>{clearTimeout(window.aiRefundTimer);window.aiRefundTimer=setTimeout(loadAiOrders,300)};$('aiOrderSearch').oninput=()=>{clearTimeout(window.aiOrderTimer);window.aiOrderTimer=setTimeout(loadAiOrders,300)};$('batchRefundTrain').oninput=()=>{clearTimeout(window.batchRefundTimer);window.batchRefundTimer=setTimeout(updateBatchRefundStops,220)};$('batchRefundFrom').onchange=updateBatchRefundToStops;$('batchRefundButton').onclick=batchRefund;$('refreshAll').onclick=()=>loadView(currentView);$('adminLogout').onclick=async()=>{try{await api('/api/admin/auth/logout',{method:'POST',body:'{}'})}finally{location.replace('/admin-login.html')}};setInterval(()=>{$('clock').textContent=new Date().toLocaleString('zh-CN',{hour12:false})},1000);setInterval(()=>{if(['overview','waitlist','buffer'].includes(currentView))loadView(currentView)},2000);
$('aiRunSearch').oninput=matchAiRun;
$('orderSort').onchange=loadOrders;
async function bootstrap(){const admin=await api('/api/admin/auth/session');$('adminDisplayName').textContent=admin.display_name||admin.username;const initialView=Object.hasOwn(meta,location.hash.slice(1))?location.hash.slice(1):'overview';showView(initialView)}bootstrap().catch(()=>{});
