const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});let data;try{data=await response.json()}catch{throw new Error('服务返回了无法解析的数据')}if(!response.ok)throw new Error(translateError(data.error||'请求失败'));return data};
const translateError=message=>({ORDER_INSUFFICIENT_INVENTORY:'当前席别已经售罄，可提交候补',ORDER_INVENTORY_CONCURRENT_CONFLICT:'余票刚刚被其他乘客锁定，请重新选择或候补',ORDER_RUN_NOT_ON_SALE:'该车次暂未开售',ORDER_PASSENGER_NOT_OWNED_OR_DISABLED:'乘车人信息不可用',WAIT_DIRECT_INVENTORY_AVAILABLE:'当前仍有余票，无需候补'}[message]||message);
let account=JSON.parse(localStorage.getItem('railflow-account')||'null'),locations=[],lastSearch=[],trainGroups=[],selectedGroup=null,selectedSeat=null,selectedPosition='',pendingBookingKey=null;

function toast(message,type='info'){const el=$('toast');el.textContent=message;el.dataset.type=type;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
function showPage(name){document.querySelectorAll('.app-page').forEach(page=>page.classList.toggle('active',page.id===`page-${name}`));window.scrollTo({top:0,behavior:'smooth'})}
function openModal(id){const modal=$(id);modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeModal(id){const modal=$(id);modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function setAccountUI(){if(!account)return;const name=account.display_name||account.passenger_name||'乘车人';$('profileName').textContent=name;$('profileAvatar').textContent=name.slice(0,1);$('welcomeName').textContent=`${name}，你好`;$('authScreen').classList.add('hidden');$('userApp').classList.remove('hidden')}

async function init(){if(account){try{account=await api(`/api/auth/account?userId=${account.user_id}`);localStorage.setItem('railflow-account',JSON.stringify(account));setAccountUI()}catch{localStorage.removeItem('railflow-account');account=null}}try{locations=await api('/api/locations');buildCities()}catch(error){toast(error.message,'error')}}
function buildCities(){const cities=[...new Set(locations.map(x=>x.city))].sort((a,b)=>a.localeCompare(b,'zh-CN'));const options=cities.map(city=>`<option value="${escapeHtml(city)}">${escapeHtml(city)}</option>`).join('');$('fromCity').innerHTML=options;$('toCity').innerHTML=options;$('fromCity').value=cities.includes('南京')?'南京':cities[0];$('toCity').value=cities.includes('上海')?'上海':cities[1]||cities[0];updateStationOptions('from');updateStationOptions('to')}
function updateStationOptions(prefix){const city=$(`${prefix}City`).value,stations=locations.filter(x=>x.city===city);$(`${prefix}Station`).innerHTML=`<option value="">全部${escapeHtml(city)}车站</option>`+stations.map(s=>`<option value="${s.station_id}">${escapeHtml(s.station_name)}站</option>`).join('')}
function locationLabel(prefix){const city=$(`${prefix}City`).value,station=$(`${prefix}Station`).selectedOptions[0];return station?.value?station.textContent:`${city} · 全部车站`}
function searchParams(){return new URLSearchParams({fromCity:$('fromCity').value,fromStation:$('fromStation').value,toCity:$('toCity').value,toStation:$('toStation').value,date:$('serviceDate').value,passengers:'1'})}

async function searchTickets(){if($('fromCity').value===$('toCity').value&&!$('fromStation').value&&!$('toStation').value)return toast('请选择不同的出发城市和到达城市','error');$('resultRoute').textContent=`${locationLabel('from')} → ${locationLabel('to')}`;$('resultSummary').textContent='正在从数据库读取实时区间余票…';$('results').innerHTML='<div class="loading-list"><i></i><i></i><i></i></div>';showPage('results');try{lastSearch=await api(`/api/search/scoped-direct?${searchParams()}`);groupTrains();$('resultSummary').textContent=`共 ${trainGroups.length} 趟列车 · 按出发时间排序 · 余票为实时快照`;renderResults()}catch(error){$('resultSummary').textContent='查询失败';$('results').innerHTML=`<div class="empty-state"><i>!</i><h3>暂时无法查询</h3><p>${escapeHtml(error.message)}</p><button data-home>返回重新选择</button></div>`;bindHomeButtons();toast(error.message,'error')}}
function groupTrains(){const map=new Map();trainGroups=[];lastSearch.forEach(row=>{let group=map.get(row.run_id);if(!group){group={runId:row.run_id,rows:[]};map.set(row.run_id,group);trainGroups.push(group)}group.rows.push(row)})}
function renderResults(){if(!trainGroups.length){$('results').innerHTML='<div class="empty-state"><i>○</i><h3>没有符合条件的列车</h3><p>尝试选择“全部车站”扩大查询范围</p><button data-home>修改行程</button></div>';bindHomeButtons();return}$('results').innerHTML=trainGroups.map((group,index)=>trainCard(group,index)).join('')}
function trainCard(group,index){const first=group.rows[0],available=group.rows.filter(r=>Number(r.can_fulfill)===1),minPrice=Math.min(...group.rows.map(r=>Number(r.amount))),fromMarker=first.from_marker||'过',toMarker=first.to_marker||'过';return `<article class="train-card" data-run="${first.run_id}"><div class="train-overview"><div class="station-time"><b>${timeOnly(first.departure_at)}</b><span><i class="marker marker-${markerClass(fromMarker)}">${fromMarker}</i>${escapeHtml(first.from_station_name)}</span></div><button class="train-line" onclick="toggleTrain(${index})"><strong>${escapeHtml(first.train_no)}</strong><span><i></i>${formatDuration(first.duration_minutes)}<i></i></span><small>席别详情 <b>⌄</b></small></button><div class="station-time arrival"><b>${timeOnly(first.arrival_at)}</b><span><i class="marker marker-${markerClass(toMarker)}">${toMarker}</i>${escapeHtml(first.to_station_name)}</span></div><div class="price-from"><b>¥${minPrice}</b><small>起</small></div><button class="book-main ${available.length?'':'wait'}" onclick="openBooking(${index})">${available.length?'预订':'候补'}</button></div><div class="seat-glance">${group.rows.map(seatGlance).join('')}</div><div class="train-details"><div class="detail-head"><span>席别</span><span>票价</span><span>余票</span><span></span></div>${group.rows.map(seatDetail).join('')}<button class="route-button" onclick="showRoute(${first.run_id})">查看途经站点与时刻 →</button></div></article>`}
function markerClass(marker){return marker==='始'?'start':marker==='终'?'end':'pass'}
function seatGlance(row){const available=Number(row.available_seats);return `<span class="glance-item ${available?'':'sold'}"><b>${escapeHtml(row.seat_type_name)}</b><em>¥${row.amount}</em><small>${available?(available>20?'有票':`${available}张`):'无票'}</small></span>`}
function seatDetail(row){const available=Number(row.can_fulfill)===1;return `<div class="detail-row"><b>${escapeHtml(row.seat_type_name)}</b><strong>¥${row.amount}</strong><span class="stock ${available?'yes':'no'}">${available?(Number(row.available_seats)>20?'有票':`余 ${row.available_seats} 张`):'无票'}</span><button onclick="selectBookingSeat('${row.run_id}','${row.seat_type_id}')">${available?'选择':'候补'}</button></div>`}
function toggleTrain(index){$('results').querySelectorAll('.train-card')[index]?.classList.toggle('expanded')}

function openBooking(index){selectedGroup=trainGroups[index];selectedSeat=selectedGroup.rows.find(r=>Number(r.can_fulfill)===1)||selectedGroup.rows[0];selectedPosition='';pendingBookingKey=null;renderConfirm();showPage('confirm')}
function selectBookingSeat(runId,seatTypeId){const index=trainGroups.findIndex(g=>String(g.runId)===String(runId));selectedGroup=trainGroups[index];selectedSeat=selectedGroup.rows.find(r=>String(r.seat_type_id)===String(seatTypeId));selectedPosition='';pendingBookingKey=null;renderConfirm();showPage('confirm')}
function renderConfirm(success=null){if(success){renderSuccess(success);return}$('confirmStepLabel').textContent='确认订单';$('confirmPageTitle').textContent='核对行程并选择座位';const first=selectedGroup.rows[0],name=account.display_name||'乘车人',available=Number(selectedSeat.can_fulfill)===1;$('confirmContent').innerHTML=`<section class="confirm-trip"><div class="confirm-time"><b>${timeOnly(first.departure_at)}</b><span>${escapeHtml(first.from_station_name)}</span></div><div class="confirm-train"><strong>${escapeHtml(first.train_no)}</strong><span><i></i>${formatDuration(first.duration_minutes)}<i></i></span><small>${escapeHtml(first.train_type)}</small></div><div class="confirm-time arrival"><b>${timeOnly(first.arrival_at)}</b><span>${escapeHtml(first.to_station_name)}</span></div></section><section class="confirm-card"><div class="confirm-section-title"><div><span>01</span><div><h2>选择席别</h2></div></div></div><div class="seat-class-grid">${selectedGroup.rows.map(row=>seatClassCard(row)).join('')}</div></section><section class="confirm-card"><div class="confirm-section-title"><div><span>02</span><div><h2>乘车人</h2></div></div></div><label class="passenger-check"><input type="checkbox" checked disabled><i>✓</i><span><b>${escapeHtml(name)}</b><small>成人票</small></span><em>本人</em></label></section><section class="confirm-card"><div class="confirm-section-title"><div><span>03</span><div><h2>偏好座位</h2></div></div><small id="positionHint">暂未选择</small></div><div id="positionPicker">${positionPicker(selectedSeat)}</div><div class="fallback-note"><i>i</i><span>${available?'偏好位置无票时，将自动分配其他空闲座位。':'当前无票，可预付并候补。'}</span></div></section><section class="submit-panel"><div><span>${available?'订单金额':'候补预付'}</span><b>¥<em id="totalPrice">${selectedSeat.amount}</em></b><small>${escapeHtml(selectedSeat.seat_type_name)} · 1 位乘客</small></div><button id="confirmOrder" onclick="${available?'confirmOrder()':'joinWaitlist()'}">${available?'提交订单':'支付并候补'} <b>→</b></button></section>`}
function seatClassCard(row){const chosen=String(row.seat_type_id)===String(selectedSeat.seat_type_id),available=Number(row.can_fulfill)===1;return `<button class="seat-class ${chosen?'selected':''} ${available?'':'sold'}" onclick="chooseSeatType('${row.seat_type_id}')"><span>${escapeHtml(row.seat_type_name)}</span><b>¥${row.amount}</b><small>${available?(Number(row.available_seats)>20?'有票':`余 ${row.available_seats} 张`):'可候补'}</small><i>✓</i></button>`}
function chooseSeatType(id){selectedSeat=selectedGroup.rows.find(r=>String(r.seat_type_id)===String(id));selectedPosition='';pendingBookingKey=null;renderConfirm()}
function allowedPositions(row){const code=String(row.seat_type_code||'').toUpperCase();if(code==='BUSINESS')return ['A','F'];if(code==='FIRST')return ['A','C','D','F'];return ['A','B','C','D','F']}
function positionPicker(row){const allowed=allowedPositions(row),left=['A','B','C'].filter(x=>allowed.includes(x)),right=['D','F'].filter(x=>allowed.includes(x));return `<div class="carriage-map"><div class="window-line"></div><div class="seat-side left">${left.map(seatButton).join('')}</div><div class="aisle"><span>过</span><span>道</span></div><div class="seat-side right">${right.map(seatButton).join('')}</div><div class="window-line"></div></div><div class="position-legend"><span><i class="window-dot"></i>A/F 靠窗</span><span><i class="aisle-dot"></i>C/D 靠过道</span>${allowed.includes('B')?'<span><i class="middle-dot"></i>B 中间</span>':''}</div>`}
function seatButton(code){return `<button class="position-seat ${selectedPosition===code?'selected':''}" onclick="choosePosition('${code}')"><i></i><b>${code}</b><small>${['A','F'].includes(code)?'靠窗':['C','D'].includes(code)?'过道':'中间'}</small></button>`}
function choosePosition(code){selectedPosition=selectedPosition===code?'':code;$('positionPicker').innerHTML=positionPicker(selectedSeat);$('positionHint').textContent=selectedPosition?`已选 ${selectedPosition} 座`:'暂未选择'}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function refreshSelectedAvailability(){const row=await api(`/api/availability?${new URLSearchParams({runId:selectedSeat.run_id,fromOrder:selectedSeat.from_order,toOrder:selectedSeat.to_order,seatTypeId:selectedSeat.seat_type_id})}`);selectedSeat.available_seats=row.available_seats;selectedSeat.can_fulfill=Number(row.available_seats)>0?'1':'0';return Number(row.available_seats)}
async function confirmOrder(){const button=$('confirmOrder');button.disabled=true;button.innerHTML='<i class="button-spinner"></i> 正在核验实时余票';try{if(await refreshSelectedAvailability()<1){pendingBookingKey=null;renderConfirm();toast('该席别刚刚售罄，已切换为候补入口','error');return}button.innerHTML='<i class="button-spinner"></i> 排队锁定席位';pendingBookingKey=pendingBookingKey||`WEB-${account.user_id}-${crypto.randomUUID()}`;const queued=await api('/api/orders/queued',{method:'POST',body:JSON.stringify({userId:account.user_id,passengerId:account.passenger_id,runId:selectedSeat.run_id,fromOrder:selectedSeat.from_order,toOrder:selectedSeat.to_order,seatTypeId:selectedSeat.seat_type_id,position:selectedPosition,idempotencyKey:pendingBookingKey})});for(let i=0;i<60;i++){const state=await api(`/api/orders/queued/${queued.booking_request_id}?userId=${account.user_id}`);if(state.request_status==='SUCCEEDED'){pendingBookingKey=null;selectedSeat.available_seats=Math.max(0,Number(selectedSeat.available_seats)-1);selectedSeat.can_fulfill=Number(selectedSeat.available_seats)>0?'1':'0';renderConfirm(state.order);if(selectedPosition&&state.order?.allocation_strategy==='FALLBACK_INVENTORY')showNotice('座位分配提示','当前剩余席位已无法满足偏好要求，已在剩余席位中为你分配。');else toast('订单已确认并完成支付','success');return}if(state.request_status==='FAILED'){pendingBookingKey=null;throw new Error(translateError(state.error_code||'订票失败'))}await wait(400)}throw new Error('请求仍在缓冲队列处理中，请稍后在订单中查看')}catch(error){await refreshSelectedAvailability().catch(()=>{});renderConfirm();toast(error.message,'error')}}
async function joinWaitlist(){const button=$('confirmOrder');button.disabled=true;button.innerHTML='<i class="button-spinner"></i> 正在支付';try{if(await refreshSelectedAvailability()>0){renderConfirm();toast('已有余票，可以直接预订','success');return}const result=await api('/api/waits',{method:'POST',body:JSON.stringify({userId:account.user_id,passengerId:account.passenger_id,runId:selectedSeat.run_id,fromOrder:selectedSeat.from_order,toOrder:selectedSeat.to_order,seatTypeId:selectedSeat.seat_type_id,position:selectedPosition,fallback:true})});showNotice('候补中',`已支付 ¥${result.amount}，可在“我的订单”查看进度。`);button.disabled=true;button.textContent='候补中'}catch(error){button.disabled=false;button.textContent='支付并候补 →';toast(error.message,'error')}}
function stationEnglish(name){const map={'上海':'SHANGHAI','上海虹桥':'SHANGHAI HONGQIAO','上海南':'SHANGHAI SOUTH','南京':'NANJING','南京南':'NANJING SOUTH','杭州':'HANGZHOU','杭州东':'HANGZHOU EAST','杭州南':'HANGZHOU SOUTH','苏州':'SUZHOU','苏州北':'SUZHOU NORTH','无锡':'WUXI','无锡东':'WUXI EAST','常州':'CHANGZHOU','常州北':'CHANGZHOU NORTH','镇江':'ZHENJIANG','镇江南':'ZHENJIANG SOUTH','南通':'NANTONG','南通西':'NANTONG WEST','宁波':'NINGBO','合肥':'HEFEI','合肥南':'HEFEI SOUTH','扬州':'YANGZHOU','扬州东':'YANGZHOU EAST'};return map[String(name)]||'RAILWAY STATION'}
function renderSuccess(order){$('confirmStepLabel').textContent='显示车票';$('confirmPageTitle').textContent='电子车票';const from=order.from_station_name,to=order.to_station_name,date=String(order.departure_at||'2026-09-07').slice(0,10).replaceAll('-','.');$('confirmContent').innerHTML=`<section class="ticket-result"><div class="success-mark">✓</div><h2>购票成功</h2><article class="rail-ticket jr-ticket"><div class="jr-watermark">CR</div><div class="jr-ticket-head"><b>特急券</b><em>LTD.EXP. (RESERVED)</em></div><div class="jr-route"><div><span>${escapeHtml(from)}</span><strong>${escapeHtml(stationEnglish(from))}</strong></div><i aria-hidden="true">→</i><div><span>${escapeHtml(to)}</span><strong>${escapeHtml(stationEnglish(to))}</strong></div></div><div class="jr-mainline"><div class="jr-date"><small>乘车日期 <em>DATE</em></small><b>${date}</b></div><div class="jr-time"><b>${timeOnly(order.departure_at)}</b><small><span>发</span><em>DEPART</em></small></div><div class="jr-time"><b>${timeOnly(order.arrival_at)}</b><small><span>到</span><em>ARRIVE</em></small></div><div class="jr-train"><small>车次 <em>TRAIN</em></small><b>${escapeHtml(order.train_no)}</b></div></div><div class="jr-band" aria-hidden="true"></div><div class="jr-details"><div class="jr-passenger"><b>${escapeHtml(order.passenger_name||account.display_name)}</b></div><div><small>席别 <em>CLASS</em></small><b>${escapeHtml(order.seat_type_name)}</b></div><div><small>车厢 <em>CAR</em></small><b>${order.carriage_no||'—'}</b></div><div><small>座位 <em>SEAT</em></small><b>${escapeHtml(order.seat_no||'已分配')}</b></div><div class="jr-fare"><small>票价 <em>FARE</em></small><b>¥${order.total_amount}</b></div></div></article><div class="success-actions"><button data-home>继续购票</button><button onclick="openOrders()">我的订单</button></div></section>`;bindHomeButtons()}
function showNotice(title,text){$('noticeTitle').textContent=title;$('noticeText').textContent=text;openModal('noticeModal')}

async function showRoute(runId){openModal('routeModal');$('routeContent').innerHTML='<div class="route-loading">正在加载经停站…</div>';try{const stops=await api(`/api/runs/${runId}/stops`);$('routeContent').innerHTML=`<div class="modal-title route-title"><span>${escapeHtml(stops[0]?.train_no||'列车')} · ROUTE</span><h2>途经站点</h2><p>列车完整运行时刻</p></div><div class="stop-table"><div class="stop-head"><span>站名</span><span>到达</span><span>出发</span><span>停留</span></div>${stops.map((s,index)=>`<div class="stop-row ${index===0||index===stops.length-1?'endpoint':''}"><span><i></i>${escapeHtml(s.station_name)}</span><span>${timeOnly(s.arrival_at)||'——'}</span><span>${timeOnly(s.departure_at)||'——'}</span><span>${s.dwell_minutes?`${s.dwell_minutes} 分`:'——'}</span></div>`).join('')}</div>`}catch(error){$('routeContent').innerHTML=`<div class="route-loading">${escapeHtml(error.message)}</div>`}}
async function openOrders(){openModal('ordersModal');$('ordersList').innerHTML='<div class="route-loading">正在读取订单…</div>';try{const [rows,waits]=await Promise.all([api(`/api/orders?userId=${account.user_id}`),api(`/api/waits?userId=${account.user_id}`)]),groups={};rows.forEach(r=>(groups[r.order_id]??=[]).push(r));const records=[...Object.values(groups).map(items=>({kind:'order',data:items[0]})),...waits.filter(w=>w.wait_status!=='FULFILLED').map(data=>({kind:'wait',data}))].sort((a,b)=>String(b.data.created_at).localeCompare(String(a.data.created_at)));$('ordersList').innerHTML=records.map(record=>record.kind==='wait'?waitCard(record.data):orderCard(record.data)).join('')||'<div class="empty-orders">还没有订单</div>'}catch(error){$('ordersList').innerHTML=`<div class="empty-orders">${escapeHtml(error.message)}</div>`}}
function orderCard(order){const waitSuccess=order.order_source==='WAITLIST'&&order.order_status==='PAID',status=waitSuccess?{text:'候补成功',cls:'green'}:statusMeta(order.order_status);let action='';if(order.order_status==='PAID')action=`<button onclick="orderAction(this,${order.order_id},'refund')">退票</button>`;if(order.order_status==='PENDING_PAYMENT')action=`<button onclick="orderAction(this,${order.order_id},'cancel')">取消订单</button>`;return `<article class="user-order"><div><span>${escapeHtml(order.train_no)}</span><em class="${status.cls}">${status.text}</em></div><h3>${escapeHtml(order.from_station_name)} <i>→</i> ${escapeHtml(order.to_station_name)}</h3><p>${escapeHtml(order.seat_type_name)} · ${order.carriage_no||'-'}车 ${escapeHtml(order.seat_no||'待分配')} · ¥${order.total_amount}</p><small>${escapeHtml(order.created_at)}</small>${action}</article>`}
function waitCard(wait){const failed=['EXPIRED','CANCELLED'].includes(wait.wait_status),status=failed?'候补失败':'候补中';return `<article class="user-order wait-order"><div><span>${escapeHtml(wait.train_no)}</span><em class="${failed?'gray':'orange'}">${status}</em></div><h3>${escapeHtml(wait.from_station_name)} <i>→</i> ${escapeHtml(wait.to_station_name)}</h3><p>${escapeHtml(wait.seat_type_name)} · ¥${wait.amount} · ${failed?'已退款':'已预付'}</p><small>${escapeHtml(wait.created_at)}</small></article>`}
function statusMeta(status){return ({PAID:{text:'已支付',cls:'green'},PENDING_PAYMENT:{text:'待支付',cls:'orange'},CANCELLED:{text:'已取消',cls:'gray'},REFUNDED:{text:'已退票',cls:'gray'},TIMEOUT:{text:'已超时',cls:'gray'}})[status]||{text:status,cls:'gray'}}
async function orderAction(button,orderId,action){if(button.disabled)return;button.disabled=true;button.textContent='处理中';try{await api(`/api/orders/${orderId}/${action}`,{method:'POST',body:JSON.stringify({userId:account.user_id})});toast(action==='refund'?'退票成功，席位已释放':'订单已取消','success');await openOrders()}catch(error){button.disabled=false;button.textContent=action==='refund'?'退票':'取消订单';toast(error.message,'error')}}
const timeOnly=value=>value?String(value).slice(11,16):'--:--',formatDuration=minutes=>`${Math.floor(Number(minutes)/60)}小时${Number(minutes)%60}分`;

function bindHomeButtons(){document.querySelectorAll('[data-home]').forEach(button=>button.onclick=()=>showPage('home'))}
$('loginForm').onsubmit=async event=>{event.preventDefault();const name=$('loginName').value.trim();if(!name)return toast('请输入姓名','error');const button=$('loginButton');button.disabled=true;button.innerHTML='<i class="button-spinner"></i> 正在进入';try{account=await api('/api/auth/simple',{method:'POST',body:JSON.stringify({name})});localStorage.setItem('railflow-account',JSON.stringify(account));setAccountUI();toast(`欢迎你，${account.display_name}`,'success')}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.innerHTML='进入系统 <b>→</b>'}};
$('togglePassword').onclick=()=>{const input=$('loginPassword'),show=input.type==='password';input.type=show?'text':'password';$('togglePassword').textContent=show?'隐藏':'显示'};$('fromCity').onchange=()=>updateStationOptions('from');$('toCity').onchange=()=>updateStationOptions('to');$('swapRoute').onclick=()=>{const fc=$('fromCity').value,fs=$('fromStation').value;$('fromCity').value=$('toCity').value;updateStationOptions('from');$('fromStation').value=$('toStation').value;$('toCity').value=fc;updateStationOptions('to');$('toStation').value=fs};$('searchTickets').onclick=searchTickets;$('modifySearch').onclick=()=>showPage('home');$('backResults').onclick=()=>{renderResults();showPage('results')};$('showOrders').onclick=openOrders;$('noticeOkay').onclick=()=>closeModal('noticeModal');$('logout').onclick=()=>{localStorage.removeItem('railflow-account');account=null;location.reload()};
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>closeModal(button.dataset.close));document.querySelectorAll('.modal').forEach(modal=>modal.onclick=event=>{if(event.target===modal)closeModal(modal.id)});document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.modal.open').forEach(modal=>closeModal(modal.id))});bindHomeButtons();init();
