const $=id=>document.getElementById(id);
let activeTab='direct',lastSearch=[],account=JSON.parse(localStorage.getItem('railflow-account')||localStorage.getItem('cr12306-account')||'null');
const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});let data;try{data=await response.json()}catch{throw new Error('服务返回了无法解析的数据')}if(!response.ok)throw new Error(translateError(data.error||'请求失败'));return data};
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function translateError(message){const map={ORDER_INVENTORY_NOT_ENOUGH:'当前席别余票不足',WAIT_INVENTORY_STILL_AVAILABLE:'当前仍有余票，无需候补',REGISTER_DOCUMENT_ALREADY_BOUND:'该模拟证件已绑定其他账户',ORDER_PASSENGER_INVALID:'乘车人不可用',ORDER_RUN_NOT_ON_SALE:'车次暂未开售'};return map[message]||message}
function toast(message,type='info'){const el=$('toast');el.textContent=message;el.dataset.type=type;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
async function sha256(text){const bytes=new TextEncoder().encode(text);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function accountUI(){if(account){$('accountBadge').textContent=`用户 #${account.user_id} · 乘车人 #${account.passenger_id}`;$('accountForm').classList.add('compact');loadOrders()}else{$('accountBadge').textContent='尚未登录演示账户'}}
async function init(){try{const [health,stations]=await Promise.all([api('/api/health'),api('/api/stations')]);$('health').innerHTML=`<i></i>${health.mysql.runs} 趟车实时开售`;$('health').classList.add('ok');for(const id of ['fromStation','toStation'])$(id).innerHTML=stations.map(s=>`<option value="${s.station_id}">${escapeHtml(s.station_name)} · ${escapeHtml(s.city)}</option>`).join('');const nj=stations.find(s=>s.station_name==='南京'||s.station_name==='南京南'),sh=stations.find(s=>s.station_name==='上海'||s.station_name==='上海虹桥');if(nj)$('fromStation').value=nj.station_id;if(sh)$('toStation').value=sh.station_id}catch(error){$('health').innerHTML='<i></i>数据库未连接';toast(error.message,'error')}accountUI()}
function params(){return new URLSearchParams({from:$('fromStation').value,to:$('toStation').value,date:$('serviceDate').value,passengers:$('passengers').value,position:$('position').value,fallback:$('fallback').checked})}
async function search(){if(!$('fromStation').value||!$('toStation').value)return toast('请选择出发站和到达站','error');if($('fromStation').value===$('toStation').value)return toast('出发站与到达站不能相同','error');const button=$('search');button.disabled=true;button.innerHTML='<span class="spinner"></span> 查询中';$('summary').textContent='正在读取实时区间余票…';$('results').innerHTML='<div class="skeleton-list">'+('<i></i>'.repeat(3))+'</div>';try{lastSearch=await api(`/api/search/${activeTab}?${params()}`);$('summary').textContent=`${stationName('fromStation')} → ${stationName('toStation')} · 找到 ${lastSearch.length} 个方案 · 余票为实时快照`;render()}catch(error){$('summary').textContent='查询失败';$('results').innerHTML='<div class="welcome-empty error"><div>!</div><h3>暂时无法查询</h3><p>'+escapeHtml(error.message)+'</p></div>';toast(error.message,'error')}finally{button.disabled=false;button.innerHTML='<span>⌕</span> 查询车票'}}
function render(){if(!lastSearch.length){$('results').innerHTML='<div class="welcome-empty"><div>○</div><h3>没有符合条件的方案</h3><p>试试调整车站、日期或座位偏好</p></div>';return}$('results').innerHTML=lastSearch.slice(0,60).map((row,index)=>activeTab==='direct'?directCard(row,index):transferCard(row,index)).join('')}
function directCard(r,i){const can=String(r.can_fulfill)==='1',remaining=Number(r.available_seats||0),urgent=remaining>0&&remaining<20;return `<article class="ticket-card"><div class="ticket-main"><div class="time-station"><b>${r.departure_at.slice(11,16)}</b><span><i class="origin-tag">始</i>${stationName('fromStation')}</span></div><button class="route-summary" onclick="showRoute(${r.run_id})"><strong>${escapeHtml(r.train_no)}</strong><span><i></i>${formatDuration(r.duration_minutes)}<i></i></span><small>查看经停 ›</small></button><div class="time-station arrival"><b>${r.arrival_at.slice(11,16)}</b><span><i class="destination-tag">终</i>${stationName('toStation')}</span></div><div class="ticket-price"><b>¥${r.amount}</b><span>起</span></div></div><div class="seat-row"><div class="seat-name"><b>${escapeHtml(r.seat_type_name)}</b><span>${$('position').value?$('position').value+' 位优先':'智能分配座位'}</span></div><div class="availability ${can?'available':'sold'}"><i></i>${can?(urgent?'仅 '+remaining+' 张':remaining>30?'有票':'余 '+remaining+' 张'):'无票'}</div><div class="distance">约 ${r.journey_distance_km} km</div><div class="ticket-actions">${can?`<button class="outline" onclick="buy(${i})">立即预订</button>`:`<button class="wait-btn" onclick="waitlist(${i})">加入候补</button>`}</div></div></article>`}
function transferCard(r){return `<article class="ticket-card transfer-card"><div class="ticket-main"><div class="time-station"><b>${r.first_departure_at.slice(11,16)}</b><span>${stationName('fromStation')}</span></div><div class="transfer-route"><strong>${escapeHtml(r.first_train_no)}</strong><span>经 ${escapeHtml(r.transfer_station_name)} 换乘 ${r.transfer_minutes} 分钟</span><strong>${escapeHtml(r.second_train_no)}</strong></div><div class="time-station arrival"><b>${r.second_arrival_at.slice(11,16)}</b><span>${stationName('toStation')}</span></div><div class="ticket-price"><b>¥${r.total_amount}</b><span>合计</span></div></div><div class="seat-row"><div class="seat-name"><b>${escapeHtml(r.first_seat_type_name)} + ${escapeHtml(r.second_seat_type_name)}</b><span>全程 ${formatDuration(r.total_duration_minutes)}</span></div><div class="availability available"><i></i>一程 ${r.first_available_seats} · 二程 ${r.second_available_seats}</div><div></div><div class="ticket-actions"><button class="outline" disabled title="联程下单待扩展">查看方案</button></div></div></article>`}
const formatDuration=minutes=>`${Math.floor(Number(minutes)/60)}小时${Number(minutes)%60}分`;
function stationName(id){return $(id).selectedOptions[0]?.textContent.split(' · ')[0]||''}
function requireAccount(){if(!account){toast('请先创建或恢复演示账户','error');$('username').focus();return false}return true}
async function buy(i){if(!requireAccount())return;if($('passengers').value!=='1')return toast('当前演示账户仅绑定 1 名乘车人','error');const r=lastSearch[i];try{await api('/api/orders',{method:'POST',body:JSON.stringify({userId:account.user_id,passengerId:account.passenger_id,runId:r.run_id,fromOrder:r.from_order,toOrder:r.to_order,seatTypeId:r.seat_type_id,position:$('position').value,fallback:$('fallback').checked})});toast('占座成功，请在 10 分钟内支付','success');await Promise.all([loadOrders(),search()])}catch(error){toast(error.message,'error')}}
async function waitlist(i){if(!requireAccount())return;if($('passengers').value!=='1')return toast('当前演示账户仅绑定 1 名乘车人','error');const r=lastSearch[i];try{await api('/api/waits',{method:'POST',body:JSON.stringify({userId:account.user_id,passengerId:account.passenger_id,runId:r.run_id,fromOrder:r.from_order,toOrder:r.to_order,seatTypeId:r.seat_type_id,position:$('position').value,fallback:$('fallback').checked})});toast('已加入候补队列，可在管理端观察队列','success')}catch(error){toast(error.message,'error')}}
async function loadOrders(){if(!account)return;try{const rows=await api(`/api/orders?userId=${account.user_id}`),groups={};rows.forEach(r=>(groups[r.order_id]??=[]).push(r));$('ordersList').innerHTML=Object.values(groups).slice(0,8).map(items=>{const o=items[0],status=statusMeta(o.order_status);let actions='';if(o.order_status==='PENDING_PAYMENT')actions=`<button class="mini primary-mini" onclick="orderAction(${o.order_id},'pay')">立即支付</button><button class="mini" onclick="orderAction(${o.order_id},'cancel')">取消</button>`;if(o.order_status==='PAID')actions=`<button class="mini" onclick="orderAction(${o.order_id},'refund')">申请退款</button>`;return `<article class="order-item"><div class="order-top"><b>${escapeHtml(o.train_no)}</b><span class="status ${status.cls}">${status.text}</span></div><div class="order-route"><span>${escapeHtml(o.from_station_name)}</span><i>→</i><span>${escapeHtml(o.to_station_name)}</span></div><p>${escapeHtml(o.seat_type_name)} · ${o.carriage_no||'-'}车 ${escapeHtml(o.seat_no||'待分配')} · ¥${o.total_amount}</p><div class="order-actions">${actions}</div></article>`}).join('')||'<p class="muted center empty-orders">暂无订单</p>'}catch(error){toast(error.message,'error')}}
function statusMeta(s){return ({PENDING_PAYMENT:{text:'待支付',cls:'warning'},PAID:{text:'已支付',cls:'success'},CANCELLED:{text:'已取消',cls:'neutral'},TIMEOUT:{text:'已超时',cls:'neutral'},REFUNDING:{text:'退款中',cls:'warning'},REFUNDED:{text:'已退款',cls:'neutral'}})[s]||{text:s,cls:'neutral'}}
async function orderAction(id,action){try{await api(`/api/orders/${id}/${action}`,{method:'POST',body:JSON.stringify({userId:account.user_id})});toast({pay:'支付成功，祝您旅途愉快',cancel:'订单已取消，库存已释放',refund:'退款成功，库存已释放'}[action],'success');await Promise.all([loadOrders(),lastSearch.length?search():Promise.resolve()])}catch(error){toast(error.message,'error')}}
async function showRoute(runId){const modal=$('routeModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('routeContent').innerHTML='<div class="route-loading">正在加载经停站…</div>';try{const stops=await api(`/api/runs/${runId}/stops`);$('routeContent').innerHTML=`<div class="route-title"><span>${escapeHtml(stops[0]?.train_no||'列车')}</span><h2>经停站信息</h2><p>${stops.length} 站 · 时刻表</p></div><div class="stop-table"><div class="stop-head"><span>站名</span><span>到达</span><span>出发</span><span>停留</span></div>${stops.map((s,i)=>`<div class="stop-row ${i===0||i===stops.length-1?'endpoint':''}"><span><i></i>${escapeHtml(s.station_name)}</span><span>${timeOnly(s.arrival_at)||'——'}</span><span>${timeOnly(s.departure_at)||'——'}</span><span>${s.dwell_minutes?`${s.dwell_minutes} 分`:'——'}</span></div>`).join('')}</div>`}catch(error){$('routeContent').innerHTML=`<div class="route-loading">${escapeHtml(error.message)}</div>`}}
function timeOnly(value){return value?String(value).slice(11,16):''}function closeRoute(){$('routeModal').classList.remove('open');$('routeModal').setAttribute('aria-hidden','true')}
document.querySelectorAll('.tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));button.classList.add('active');activeTab=button.dataset.tab;if($('fromStation').value)search()});
document.querySelectorAll('#positionGroup button').forEach(button=>button.onclick=()=>{document.querySelectorAll('#positionGroup button').forEach(x=>x.classList.remove('active'));button.classList.add('active');$('position').value=button.dataset.value});
$('swap').onclick=()=>{const x=$('fromStation').value;$('fromStation').value=$('toStation').value;$('toStation').value=x};$('search').onclick=search;$('refreshOrders').onclick=loadOrders;
$('register').onclick=async()=>{try{const data=await api('/api/register',{method:'POST',body:JSON.stringify({username:$('username').value,passwordHash:await sha256($('password').value),passengerName:$('passengerName').value,documentToken:$('documentToken').value})});account=data;localStorage.setItem('railflow-account',JSON.stringify(account));accountUI();toast('演示账户已就绪','success')}catch(error){toast(error.message,'error')}};
$('routeModal').onclick=e=>{if(e.target===$('routeModal'))closeRoute()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeRoute()});init();
